
// 1. https://www.artevenue.com/art-print/198955/
// 2. https://www.artevenue.com/art-print/307511/
// 3. https://www.artevenue.com/art-print/397637/
// 4. https://www.artevenue.com/art-print/149103/
// 5. https://www.artevenue.com/art-print/165917/
// 6. https://www.artevenue.com/art-print/12037/
// 7. https://www.artevenue.com/art-print/12038/
// 8. https://www.artevenue.com/art-print/13428/
// 9. https://www.artevenue.com/art-print/13429/
// 10. https://www.artevenue.com/art-print/19080/
// 11. https://www.artevenue.com/art-print/19191/
// 12. https://www.artevenue.com/art-print/19381/
// 13. https://www.artevenue.com/art-print/19382/
// 14. https://www.artevenue.com/art-print/21190/
// 15. https://www.artevenue.com/art-print/29009/
// 16. https://www.artevenue.com/art-print/23675/
// 17. https://www.artevenue.com/art-print/30473/
// 18. https://www.artevenue.com/art-print/30476/
// 19. https://www.artevenue.com/art-print/31660/
// 20. https://www.artevenue.com/art-print/31687/
// 21. https://www.artevenue.com/art-print/31688/
// 22. https://www.artevenue.com/art-print/31689/
// 23. https://www.artevenue.com/art-print/32636/
// 24. https://www.artevenue.com/art-print/36090/
// 25. https://www.artevenue.com/art-print/36224/
// 26. https://www.artevenue.com/art-print/36365/
// 27. https://www.artevenue.com/art-print/36708/
// 28. https://www.artevenue.com/art-print/36721/
// 29. https://www.artevenue.com/art-print/37030/
// 30. https://www.artevenue.com/art-print/42748/


export default {
    products: [{
            _id: "1",
            name: "BLACK HORSES",
            image: "./photos/1.png",
            price: 22.49,
            rating: 4.5,
            reviews: [],
            buyers: [],
        },{
            _id: "2",
            name: "FALL AT SOBA COMMONE",
            image: "./photos/2.png",
            price: 24.99,
            rating: 4.3,
            reviews: [],
            buyers: [],
        },{
            _id: "3",
            name: "BLONDE BRUSH",
            image: "./photos/3.png",
            price: 12.99,
            rating: 3.8,
            reviews: [],
            buyers: [],
        },{
            _id: "4",
            name: "WATER LILY POND",
            image: "./photos/4.png",
            price: 30.49,
            rating: 4.7,
            reviews: [],
            buyers: [],
        },{
            _id: "5",
            name: "PASTORAL LANDSCAPE",
            image: "./photos/5.png",
            price: 22.99,
            rating: 3.6,
            reviews: [],
            buyers: [],
        },{
            _id: "6",
            name: "AFRICAN KRAAL",
            image: "./photos/6.png",
            price: 27.99,
            rating: 4.2,
            reviews: [],
            buyers: [],
        },{
            _id: "7",
            name: "THE DRUM",
            image: "./photos/7.png",
            price: 32.99,
            rating: 4.5,
            reviews: [],
            buyers: [],
        },{
            _id: "8",
            name: "ADVICE I",
            image: "./photos/8.png",
            price: 34.99,
            rating: 4.8,
            reviews: [],
            buyers: [],
        },{
            _id: "9",
            name: "ADVICE II",
            image: "./photos/9.png",
            price: 38.99,
            rating: 4.6,
            reviews: [],
            buyers: [],
        },{
            _id: "10",
            name: "EXOTIC GARDEN",
            image: "./photos/10.png",
            price: 29.99,
            rating: 4.2,
            reviews: [],
            buyers: [],
        },{
            _id: "11",
            name: "MOJAVE ROAD CROP",
            image: "./photos/11.png",
            price: 23.49,
            rating: 4.8,
            reviews: [],
            buyers: [],
        },{
            _id: "12",
            name: "GAME OVER",
            image: "./photos/12.png",
            price: 49.99,
            rating: 4.3,
            reviews: [],
            buyers: [],
        },{
            _id: "13",
            name: "BROKEN DREAMS",
            image: "./photos/13.png",
            price: 17.99,
            rating: 3.9,
            reviews: [],
            buyers: [],
        },{
            _id: "14",
            name: "BURNT ORANGE",
            image: "./photos/14.png",
            price: 28.49,
            rating: 4.4,
            reviews: [],
            buyers: [],
        },{
            _id: "15",
            name: "COLORFUL FLOWERS",
            image: "./photos/15.png",
            price: 16.99,
            rating: 3.9,
            reviews: [],
            buyers: [],
        },{
            _id: "16",
            name: "MARBLE",
            image: "./photos/16.png",
            price: 35.99,
            rating: 4.4,
            reviews: [],
            buyers: [],
        },{
            _id: "17",
            name: "LEGENDS",
            image: "./photos/17.png",
            price: 35.99,
            rating: 4.4,
            reviews: [],
            buyers: [],
        },{
            _id: "18",
            name: "TRIBECA",
            image: "./photos/18.png",
            price: 18.49,
            rating: 4.8,
            reviews: [],
            buyers: [],
        },{
            _id: "19",
            name: "ABSTRACT DAY",
            image: "./photos/19.png",
            price: 49.99,
            rating: 3.3,
            reviews: [],
            buyers: [],
        },{
            _id: "20",
            name: "HAPPY LANDING",
            image: "./photos/20.png",
            price: 120.99,
            rating: 4.7,
            reviews: [],
            buyers: [],
        },{
            _id: "21",
            name: "SILENT GLOW",
            image: "./photos/21.png",
            price: 14.99,
            rating: 4.9,
            reviews: [],
            buyers: [],
        },{
            _id: "22",
            name: "SPLENDID GLOW",
            image: "./photos/22.png",
            price: 14.99,
            rating: 4.4,
            reviews: [],
            buyers: [],
        },{
            _id: "23",
            name: "DIZZY AT THE EDGE",
            image: "./photos/23.png",
            price: 27.99,
            rating: 4.8,
            reviews: [],
            buyers: [],
        },{
            _id: "24",
            name: "RED POPPY FOREST",
            image: "./photos/24.png",
            price: 54.49,
            rating: 4.6,
            reviews: [],
            buyers: [],
        },{
            _id: "25",
            name: "RAINFALL",
            image: "./photos/25.png",            
            price: 28.99,
            rating: 4.4,
            reviews: [],
            buyers: [],
        },{
            _id: "26",
            name: "SUNRISE BY THE SEA",
            image: "./photos/26.png",            
            price: 23.49,
            rating: 3.9,
            reviews: [],
            buyers: [],
        },{
            _id: "27",
            name: "WINDTHREAD",
            image: "./photos/27.png",            
            price: 32.49,
            rating: 4.4,
            reviews: [],
            buyers: [],
        },{
            _id: "28",
            name: "WHITE TULIPS",
            image: "./photos/28.png",            
            price: 26.99,
            rating: 4.1,
            reviews: [],
            buyers: [],
        },{
            _id: "29",
            name: "COLORS OF IRIS",
            image: "./photos/29.png",            
            price: 58.49,
            rating: 4.5,
            reviews: [],
            buyers: [],
        },{
            _id: "30",
            name: "COLORS IN SPACE",
            image: "./photos/30.png",            
            price: 72.99,
            rating: 4.2,
            reviews: [],
            buyers: [],
        },{
            _id: "31",
            name: "FITTED BLAZER",
            description: "Fitted blazer in woven fabric with notched lapels, welt front pockets, and decorative buttons at cuffs. Vent at back. Lined.",
            category: ["blazer","black","formal","smart"],
            image: "/imgs/31.jpg",
            price: 39.99,
            rating: 4.2,
            reviews: [],
            buyers: [],
        },{
            _id: "32",
            name: "FAUX SHEARLING-LINED JACKET",
            description: "Jacket in faux suede with faux leather details. Collar with tabs and metal buckles, zip at front, and front pockets with zip. Faux shearling lining.",
            category: ["jacket","black","trendy","winter"],
            image: "/imgs/32.jpg",
            price: 79.99,
            rating: 4.5,
            reviews: [],
            buyers: [],
        },{
            _id: "33",
            name: "JERSEY ROMPER",
            description: "Sleeveless romper in jersey. Box-neck, buttons at top, and narrow, adjustable shoulder straps. Concealed, elasticized seam at waist. Unlined.",
            category: ["romper","color","trendy","summer"],
            image: "/imgs/33.jpeg",
            price: 39.99,
            rating: 4.2,
            reviews: [],
            buyers: [],
        },{
            _id: "34",
            name: "CHECKERED COTTON SHIRT",
            description: "Straight-cut shirt in woven cotton fabric. Collar, buttons at front, open chest pocket, and yoke at back with pleat. Long sleeves with button at cuffs. Rounded hem, slightly longer at back.",
            category: ["shirt","color","trendy","summer"],
            image: "/imgs/34.jpg",
            price: 19.99,
            rating: 4.0,
            reviews: [],
            buyers: [],
        },{
            _id: "35",
            name: "FLORAL PATTERNED BLOUSE",
            description: "Blouse in woven, textured fabric with covered buttons at back of neck. Long, voluminous puff sleeves tapered at cuffs.",
            category: ["top","blouse","trendy","summer","color","smart"],
            image: "/imgs/35.jpg",
            price: 24.99,
            rating: 3.7,
            reviews: [],
            buyers: [],
        },{
            _id: "36",
            name: "DENIM OVERALLS",
            description: "Overalls in washed denim. Wide suspenders with metal fasteners. Bib pocket, front and back pockets, smaller pockets on one leg, and a loop on other leg. Seam at waist with buttons at sides, mock fly, and straight, wide legs. Content is partly recycled.",
            category: ["jumpsuit","black","trendy","summer"],
            image: "/imgs/36.jpg",
            price: 39.99,
            rating: 4.6,
            reviews: [],
            buyers: [],
        },{
            _id: "37",
            name: "SLIM FIT LINEN-BLEND BLAZER",
            description: "Single-breasted blazer in woven fabric made from a linen and cotton blend. Narrow, notched lapels with decorative buttonhole, two buttons at front, and decorative buttons at cuffs. Welt chest pocket, front pockets with flap, and three inner pockets, one with button. Vent at back. Lined. Slim Fit – tapered at chest and waist with slightly narrower sleeves for a tailored silhouette.",
            category: ["blazer","color","formal","smart"],
            image: "/imgs/37.jpg",
            price: 74.99,
            rating: 4.7,
            reviews: [],
            buyers: [],
        },{
            _id: "38",
            name: "MESH SHIRT",
            description: "Fitted shirt in airy mesh with a collar, buttons down the front and long sleeves with buttoned cuffs.",
            category: ["shirt","top","blouse","black"],
            image: "/imgs/38.jpg",
            price: 19.99,
            rating: 3.9,
            reviews: [],
            buyers: [],
        },{
            _id: "39",
            name: "RIB KNIT CARDIGAN",
            description: "Boxy, long-sleeved cardigan in soft, rib-knit fabric with wool content. V-neck, buttons at front, and dropped shoulders. Ribbing at cuffs and hem. Polyester content is recycled.",
            category: ["sweater","color","trendy","winter"],
            image: "/imgs/39.jpg",
            price: 34.99,
            rating: 4.8,
            reviews: [],
            buyers: [],
        },{
            _id: "40",
            name: "SKINNY FIT BLAZER",
            description: "Single-breasted blazer in woven stretch fabric with narrow, notched lapels. Chest pocket, front pockets with flap, and an inner pocket. Decorative buttons at cuffs and a vent at back. Lined. Skinny Fit – slightly shorter style, shaped at chest, tapered sharply at waist, combined with narrow shoulders and sleeves for a completely tailored silhouette.",
            category: ["blazer","black","formal","smart"],
            image: "/imgs/40.jpg",
            price: 69.99,
            rating: 4.7,
            reviews: [],
            buyers: [],
        },{
            _id: "41",
            name: "SLIM FIT SUIT VEST",
            description: "Suit vest in woven fabric with shiny woven fabric at back. Buttons at front, a chest pocket, welt front pockets, and adjustable tab at back. Lined.",
            category: ["vest","color","formal","smart"],
            image: "/imgs/41.jpg",
            price: 24.99,
            rating: 4.4,
            reviews: [],
            buyers: [],
        },{
            _id: "42",
            name: "CYCLING SHORTS",
            description: "Cycling shorts in stretch cotton jersey with a high waist and elasticized waistband.",
            category: ["shorts","black","sport","summer"],
            image: "/imgs/42.jpg",
            price: 5.99,
            rating: 4.9,
            reviews: [],
            buyers: [],
        },{
            _id: "43",
            name: "PRINTED SWEATSHIRT",
            description: "Straight-style top in sweatshirt fabric with a print motif at the top. Relaxed fit with low dropped shoulders, long, wide sleeves and ribbing around the neckline and cuffs. Soft brushed inside.",
            category: ["sweatshirt","color","trendy","winter"],
            image: "/imgs/43.jpg",
            price: 24.99,
            rating: 4.1,
            reviews: [],
            buyers: [],
        },{
            _id: "44",
            name: "COTTON POLO SHIRT",
            description: "Polo shirt in cotton piqué. Ribbed collar, button placket, and short sleeves with ribbed cuffs. Slits at sides.",
            category: ["tshirt","color","smart","summer"],
            image: "/imgs/44.jpg",
            price: 14.99,
            rating: 4.3,
            reviews: [],
            buyers: [],
        },{
            _id: "45",
            name: "HIGH WAISTED DENIM SHORTS",
            description: "Short, 5-pocket shorts in washed denim with heavily distressed details. High waist and button fly. Sewn foldover cuffs with raw-edge, cut-off hems.",
            category: ["shorts","denim","color","summer"],
            image: "/imgs/45.jpg",
            price: 9.99,
            rating: 4.5,
            reviews: [],
            buyers: [],
        },
    ]
}